services:
  logai-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logai-web
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/var/log/logai
      - ./uploads:/app/uploads
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - logai-network

networks:
  logai-network:
    driver: bridge 