version: '3.8'

services:
  logai-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/workspace/logs
      - ./uploads:/workspace/uploads
      - ./logai.db:/workspace/logai.db  # DuckDB is now handled in Python
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      # Add AI provider API keys as needed
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      # Default provider
      - DEFAULT_PROVIDER=${DEFAULT_PROVIDER:-openai}
    depends_on:
      - qdrant
    networks:
      - logai-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # This ensures the frontend knows where to find the backend inside the Docker network
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - logai-api
    networks:
      - logai-network

  # Qdrant for vector similarity search
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - logai-network

volumes:
  qdrant_data:

networks:
  logai-network:
    driver: bridge 