version: '3.8'

services:
  logai-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/workspace/logs
      - ./uploads:/workspace/uploads
      - ./logai.db:/workspace/logai.db  # DuckDB is now handled in Python
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      # Add AI provider API keys as needed
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      # Default provider
      - DEFAULT_PROVIDER=${DEFAULT_PROVIDER:-openai}
    depends_on:
      - milvus
    networks:
      - logai-network

  # Milvus for vector similarity search (used from Python)
  milvus:
    image: milvusdb/milvus:v2.3.3
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      - ETCD_ENDPOINTS=etcd:2379
    command: ["milvus", "run", "standalone"]
    depends_on:
      - etcd
    networks:
      - logai-network

  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - etcd_data:/etcd
    networks:
      - logai-network

volumes:
  milvus_data:
  etcd_data:

networks:
  logai-network:
    driver: bridge 